Repository silverstripe/silverstripe-contentreview, pull requests merged in 2018-06, with the labels that each got.

#54 FIX Ensure QueuedJob health check doesn't kill long running review jobs
  code/jobs/ContentReviewNotificationJob.php
Labels: affects/v3

#87 Constraint 4.0.x release line to SilverStripe 4.0 and 4.1, use contentreview 4.1 for SS 4.2+
  composer.json
Labels: affects/v4, change/patch

#86 BUG Update modal API for Reactstrap in SilverStripe 4.2, bump constraint
  .travis.yml
  client/dist/js/contentreview.js
  client/src/bundles/ContentReviewForm.js
  composer.json
  src/Extensions/SiteTreeContentReview.php
  src/Forms/ReviewContentHandler.php
Labels: affects/v4, change/minor
